# https://github.com/docker/awesome-compose/tree/master/prometheus-grafana

services:
  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yaml"]
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
