global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: metrics-project
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 192.168.0.19:4689
