apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql

spec:
  # minReadySeconds: 10 # deploy delay of 10 seconds
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: "mysql:5"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
            - name: MYSQL_DATABASE
              value: fleetman
