apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb

spec:
  # minReadySeconds: 10 # deploy delay of 10 seconds
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: "mongo:3.6.5"
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
