apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      targetPort: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616
      targetPort: 61616

  #type: LoadBalancer
  #type: ClusterIP # internal service
  type: NodePort # exposed
