apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp

spec:
  # minReadySeconds: 10 # deploy delay of 10 seconds
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp

    spec:
      containers:
        - name: webapp
          image: "richardchesterwood/k8s-fleetman-webapp-angular:release2"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
